import type { Lead } from "@/lib/types";

export const demoLeads: Lead[] = [
  {
    id: "demo-01",
    business_name: "Northline Dental Studio",
    contact_name: "Maya Patel",
    phone: "+44 20 7946 1182",
    email: "maya@northlinedental.co.uk",
    need: "Missed-call recovery",
    estimated_value: 7200,
    status: "Interested",
    notes: "Asked for examples before booking.",
    created_by: "Louis Bish",
    created_at: "2026-05-18T08:10:00.000Z",
  },
  {
    id: "demo-02",
    business_name: "Harbour Skin Clinic",
    contact_name: "Ella Morgan",
    phone: "+44 20 7946 2201",
    email: "ella@harbourskin.co.uk",
    need: "Lead follow-up",
    estimated_value: 5600,
    status: "Call Booked",
    notes: "Call set for Thursday morning.",
    created_by: "Louis Bish",
    created_at: "2026-05-18T07:42:00.000Z",
  },
  {
    id: "demo-03",
    business_name: "Atlas Roofing",
    contact_name: "James Carter",
    phone: "+44 161 555 0182",
    email: "james@atlasroofing.co.uk",
    need: "Inbound enquiry handling",
    estimated_value: 9800,
    status: "New",
    notes: "Website form lead. Needs first touch.",
    created_by: "Louis Bish",
    created_at: "2026-05-17T16:30:00.000Z",
  },
  {
    id: "demo-04",
    business_name: "Willow Aesthetics",
    contact_name: "Sophie Reed",
    phone: "+44 113 555 0148",
    email: "sophie@willowaesthetics.co.uk",
    need: "Consultation reminders",
    estimated_value: 4100,
    status: "Contacted",
    notes: "Left voicemail and sent email.",
    created_by: "Louis Bish",
    created_at: "2026-05-17T15:05:00.000Z",
  },
  {
    id: "demo-05",
    business_name: "Crown Physio",
    contact_name: "Daniel Hughes",
    phone: "+44 121 555 0194",
    email: "daniel@crownphysio.co.uk",
    need: "No-show reduction",
    estimated_value: 6300,
    status: "Won",
    notes: "Ready to onboard next week.",
    created_by: "Louis Bish",
    created_at: "2026-05-17T13:18:00.000Z",
  },
  {
    id: "demo-06",
    business_name: "Oak & Stone Kitchens",
    contact_name: "Priya Shah",
    phone: "+44 20 7946 4410",
    email: "priya@oakstonekitchens.co.uk",
    need: "Quote chasing",
    estimated_value: 8400,
    status: "Interested",
    notes: "Wants pricing summary by email.",
    created_by: "Louis Bish",
    created_at: "2026-05-17T12:22:00.000Z",
  },
  {
    id: "demo-07",
    business_name: "Elm Street Vets",
    contact_name: "Rachel Green",
    phone: "+44 117 555 0120",
    email: "rachel@elmstreetvets.co.uk",
    need: "Reception overflow",
    estimated_value: 6900,
    status: "Contacted",
    notes: "Owner requested a callback Friday.",
    created_by: "Louis Bish",
    created_at: "2026-05-16T17:11:00.000Z",
  },
  {
    id: "demo-08",
    business_name: "Summit Legal",
    contact_name: "Oliver Grant",
    phone: "+44 20 7946 7722",
    email: "oliver@summitlegal.co.uk",
    need: "New enquiry triage",
    estimated_value: 12000,
    status: "Call Booked",
    notes: "Decision maker joining discovery.",
    created_by: "Louis Bish",
    created_at: "2026-05-16T14:48:00.000Z",
  },
  {
    id: "demo-09",
    business_name: "Brighton Orthodontics",
    contact_name: "Nina Clarke",
    phone: "+44 1273 555 771",
    email: "nina@brightonortho.co.uk",
    need: "Lead speed-to-contact",
    estimated_value: 7600,
    status: "New",
    notes: "Instagram enquiry from founder.",
    created_by: "Louis Bish",
    created_at: "2026-05-16T11:02:00.000Z",
  },
  {
    id: "demo-10",
    business_name: "Forge Fitness",
    contact_name: "Ben Walker",
    phone: "+44 161 555 7790",
    email: "ben@forgefitness.co.uk",
    need: "Trial conversion",
    estimated_value: 3500,
    status: "Lost",
    notes: "Timing issue; revisit next quarter.",
    created_by: "Louis Bish",
    created_at: "2026-05-15T16:55:00.000Z",
  },
  {
    id: "demo-11",
    business_name: "Luna Medispa",
    contact_name: "Aisha Khan",
    phone: "+44 20 7946 8801",
    email: "aisha@lunamedispa.co.uk",
    need: "Consultation nurture",
    estimated_value: 9100,
    status: "Interested",
    notes: "Asked about multilingual handling.",
    created_by: "Louis Bish",
    created_at: "2026-05-15T14:13:00.000Z",
  },
  {
    id: "demo-12",
    business_name: "Horizon Wealth",
    contact_name: "Marcus Lee",
    phone: "+44 20 7946 3304",
    email: "marcus@horizonwealth.co.uk",
    need: "Lead qualification",
    estimated_value: 15000,
    status: "Call Booked",
    notes: "Strong fit. Wants compliance overview.",
    created_by: "Louis Bish",
    created_at: "2026-05-15T10:37:00.000Z",
  },
  {
    id: "demo-13",
    business_name: "Silverline Care",
    contact_name: "Hannah Brooks",
    phone: "+44 113 555 7730",
    email: "hannah@silverlinecare.co.uk",
    need: "Inbound call coverage",
    estimated_value: 6700,
    status: "Contacted",
    notes: "Sent case study after intro call.",
    created_by: "Louis Bish",
    created_at: "2026-05-14T17:20:00.000Z",
  },
  {
    id: "demo-14",
    business_name: "Redwood Estate Agents",
    contact_name: "Tom Fraser",
    phone: "+44 20 7946 9900",
    email: "tom@redwoodagents.co.uk",
    need: "Viewing follow-up",
    estimated_value: 5300,
    status: "New",
    notes: "Referral from existing client.",
    created_by: "Louis Bish",
    created_at: "2026-05-14T13:45:00.000Z",
  },
  {
    id: "demo-15",
    business_name: "Pine Dental Group",
    contact_name: "Laura Evans",
    phone: "+44 117 555 3391",
    email: "laura@pinedental.co.uk",
    need: "Recall campaigns",
    estimated_value: 8800,
    status: "Won",
    notes: "Verbal yes; paperwork pending.",
    created_by: "Louis Bish",
    created_at: "2026-05-14T09:12:00.000Z",
  },
  {
    id: "demo-16",
    business_name: "Cedar Accounting",
    contact_name: "George Mills",
    phone: "+44 121 555 2288",
    email: "george@cedaraccounting.co.uk",
    need: "New lead intake",
    estimated_value: 4700,
    status: "Lost",
    notes: "Already committed elsewhere.",
    created_by: "Louis Bish",
    created_at: "2026-05-13T16:02:00.000Z",
  },
  {
    id: "demo-17",
    business_name: "Bloom Nursery",
    contact_name: "Isla Turner",
    phone: "+44 20 7946 6642",
    email: "isla@bloomnursery.co.uk",
    need: "Parent enquiry handling",
    estimated_value: 3900,
    status: "Interested",
    notes: "Needs partner approval.",
    created_by: "Louis Bish",
    created_at: "2026-05-13T11:51:00.000Z",
  },
  {
    id: "demo-18",
    business_name: "Peak Chiropractic",
    contact_name: "Samir Ahmed",
    phone: "+44 161 555 9921",
    email: "samir@peakchiro.co.uk",
    need: "Missed enquiry follow-up",
    estimated_value: 6100,
    status: "Contacted",
    notes: "Good response on first touch.",
    created_by: "Louis Bish",
    created_at: "2026-05-13T09:26:00.000Z",
  },
  {
    id: "demo-19",
    business_name: "The Smile Rooms",
    contact_name: "Chloe Martin",
    phone: "+44 20 7946 2244",
    email: "chloe@thesmilerooms.co.uk",
    need: "Treatment plan follow-up",
    estimated_value: 10200,
    status: "Call Booked",
    notes: "Founder wants quick rollout.",
    created_by: "Louis Bish",
    created_at: "2026-05-12T15:41:00.000Z",
  },
  {
    id: "demo-20",
    business_name: "Westbridge Solicitors",
    contact_name: "Amelia Scott",
    phone: "+44 20 7946 5508",
    email: "amelia@westbridgesolicitors.co.uk",
    need: "Consultation booking",
    estimated_value: 13400,
    status: "New",
    notes: "Cold lead from outbound list.",
    created_by: "Louis Bish",
    created_at: "2026-05-12T10:08:00.000Z",
  },
];
